name: cppcheck

on:
  push:
    branches:
      - main
      - develop
      - 'release/**'
      - 'feature/**'
  pull_request:
    branches:
      - main
      - develop
      - 'release/**'
      - 'feature/**'
  workflow_dispatch:

jobs:
  cppcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install cppcheck tool
        run: |
          sudo apt-get update
          sudo apt-get install cppcheck

      - name: Execute cppcheck
        run: cppcheck --error-exitcode=1 --quiet .         
